### PR TITLE
Chore/config project

### LINKED ISSUE #1: Criar uma estrutura para Code Trouble
### **Contexto**  
O time de Mobile deverá criar a estrutura inicial do repositório utilizando a versão mais atualizada do **React Native** com suporte a **TypeScript**, configurando o projeto para builds futuras em **Android** e **iOS**. O foco deve ser garantir uma base sólida, otimizada para performance e escalabilidade.

### **História do Usuário**  
Como desenvolvedor Mobile,  
Quero criar a estrutura inicial do repositório,  
Para garantir que o projeto tenha uma base sólida, performática e pronta para builds futuras.

---

## **Objetivos**  
1. Inicializar o repositório com a versão atualizada de React Native e TypeScript.  
2. Configurar os arquivos de build para Android e iOS.  
3. Garantir que a estrutura inicial suporte boas práticas de performance e escalabilidade.  

---

## **Critérios de Aceite**

- **Dado** que o repositório foi inicializado,  
  **Quando** analisado,  
  **Então** estará configurado com React Native e TypeScript na versão mais atualizada.  

- **Dado** que a estrutura do projeto foi configurada,  
  **Quando** as builds forem executadas,  
  **Então** será possível compilar para Android e iOS.  

- **Dado** que as boas práticas de performance foram aplicadas,  
  **Quando** o repositório for avaliado,  
  **Então** estará otimizado e escalável.  

---

### Checklist de Tarefas  

1. **Inicializar o projeto**
   - [x] Criar o repositório no GitHub com o nome adequado.  
   - [x] Configurar o projeto com React Native na versão mais recente.  
   - [x] Adicionar suporte ao TypeScript.  

2. **Configurar builds**
   - [x] Configurar arquivos para build em Android.  
   - [ ] Configurar arquivos para build em iOS.  
   - [ ] Testar builds iniciais para ambas as plataformas.  

3. **Organizar a estrutura do projeto**
   - [x] Criar pastas para organização de código (e.g., `src`, `components`, `screens`, `services`).  
   - [ ] Configurar aliases para pastas principais usando `tsconfig.json`.  
   - [ ] Adicionar um README inicial descrevendo a estrutura do projeto.  

4. **Otimizar para performance**
   - [x] Configurar caching de assets (imagens, fontes, etc.).  
   - [x] Habilitar configurações de performance recomendadas no React Native.  
   - [x] Adicionar suporte ao `Hermes` (se aplicável).  

5. **Validar o setup**
   - [ ] Garantir que o projeto compila sem erros em Android e iOS.  
   - [ ] Testar a execução do projeto em emuladores para ambas as plataformas.  
   - [x] Subir a estrutura inicial para o repositório remoto no GitHub.  

---

## **Critérios de Avaliação**

- **Versão Atualizada:** O repositório utiliza a versão mais recente do React Native e TypeScript.  
- **Builds Configurados:** O projeto está preparado para builds em Android e iOS.  
- **Estrutura Clara:** A estrutura do repositório é organizada e escalável para novos desenvolvimentos.  
- **Performance:** Configurações de performance foram aplicadas para otimizar o projeto.  

---

### PR DESCRIPTION
**Pull request by henriquepablo**
# Code Trouble - Pull Request (Mobile)

---

### **Description**

- **What was done?**  structure folders, config to build in ANDROID
- **Why was it done?**  to init project

---

### **Change Type**

- [ ] Bug fix  
- [ ] New feature  
- [x] Code improvement  
- [ ] Documentation  

---

#### **Platform Testing**
- [x] Have you tested on an Android emulator?  
- [ ] Have you tested on an iOS simulator?  
- [x] Have you tested on a physical Android device?  
- [ ] Have you tested on a physical iOS device?  

#### **Performance**
- [ ] Have you verified app performance (e.g., animations, loading times)?  
- [ ] Have you optimized assets (e.g., images, icons)?  

#### **Security**
- [x] Were tests added for new features or changes?  
- [ ] Was the documentation updated (if needed)?  

#### **Code Quality**
- [ ] Have you followed the project’s linting and formatting rules?  
- [ ] Are all commits clear and meaningful?  
- [ ] Have you ensured clean and modular code structure?  

#### **Accessibility**
- [x] Have you tested for screen reader compatibility?  
- [ ] Have you ensured proper contrast ratios and font scaling?  

---

### **Screenshots (if applicable)**

_Add screenshots of your changes on different devices/platforms if necessary._

---

### CODE REVIEW

**Comment by lucascorreaa** [comment]
@henriquepablo preenche a PR, é um padrão para termos no repositório

**Comment by lucascorreaa** [comment]
@henriquepablo responde a PR, preenche ela, é um padrão para termos no repositório

**Comment by henriquepablo** [comment]
@lucascorreaa 

Qual deve ser a forma correta de preencher? Estava colocando um X dentro do [ ].

Exemplo: 

[ x ] Have you tested on a physical Android device?

**Comment by lucascorreaa** [comment]
só clicar kkkkkkkkkkk

image

**Comment by henriquepablo** [comment]
Caraca kkkkkkkk

**Pull request merged**
